export default {
  darkMode: 'class',
  content: ['./index.html', './src/**/*.{ts,tsx}'],
  theme: {
    extend: {
      colors: {
        // Shadcn/UI base colors
        border: 'hsl(var(--border))',
        input: 'hsl(var(--input))',
        ring: 'hsl(var(--ring))',
        background: 'hsl(var(--background))',
        foreground: 'hsl(var(--foreground))',
        primary: {
          DEFAULT: 'hsl(var(--primary))',
          foreground: 'hsl(var(--primary-foreground))',
        },
        secondary: {
          DEFAULT: 'hsl(var(--secondary))',
          foreground: 'hsl(var(--secondary-foreground))',
        },
        destructive: {
          DEFAULT: 'hsl(var(--destructive))',
          foreground: 'hsl(var(--destructive-foreground))',
        },
        muted: {
          DEFAULT: 'hsl(var(--muted))',
          foreground: 'hsl(var(--muted-foreground))',
        },
        accent: {
          DEFAULT: 'hsl(var(--accent))',
          foreground: 'hsl(var(--accent-foreground))',
        },
        popover: {
          DEFAULT: 'hsl(var(--popover))',
          foreground: 'hsl(var(--popover-foreground))',
        },
        card: {
          DEFAULT: 'hsl(var(--card))',
          foreground: 'hsl(var(--card-foreground))',
        },
        
        // Original custom colors
        "on-primary": "#ffffff",
        "tertiary": "#233841",
        "on-tertiary-container": "#aac0cc",
        "tertiary-fixed-dim": "#b4cad6",
        "tertiary-fixed": "#cfe6f2",
        "surface-container-lowest": "#ffffff",
        "outline-variant": "#c0c8ca",
        "background": "hsl(var(--background))",
        "secondary-container": "#fc820c",
        "primary-fixed-dim": "#9acfda",
        "on-error": "#ffffff",
        "primary": "hsl(var(--primary))",
        "surface-container-high": "#e7e8e9",
        "on-primary-container": "#90c5cf",
        "surface-tint": "#30666f",
        "surface-container": "#edeeef",
        "secondary-fixed-dim": "#ffb786",
        "inverse-on-surface": "#f0f1f2",
        "on-tertiary-fixed-variant": "#354a53",
        "on-surface": "#191c1d",
        "on-secondary": "#ffffff",
        "outline": "#70797a",
        "on-primary-fixed-variant": "#134e57",
        "surface-container-low": "#f3f4f5",
        "inverse-surface": "#2e3132",
        "primary-container": "#1a535c",
        "on-secondary-fixed-variant": "#723600",
        "tertiary-container": "#3a4f59",
        "on-error-container": "#93000a",
        "on-secondary-container": "#5e2c00",
        "on-primary-fixed": "#001f24",
        "surface-bright": "#f8f9fa",
        "surface-variant": "#e1e3e4",
        "surface-container-highest": "#e1e3e4",
        "on-secondary-fixed": "#311300",
        "primary-fixed": "#b6ecf6",
        "on-surface-variant": "#40484a",
        "on-background": "#191c1d",
        "secondary": "hsl(var(--secondary))",
        "error": "#ba1a1a",
        "inverse-primary": "#9acfda",
        "secondary-fixed": "#ffdcc6",
        "on-tertiary": "#ffffff",
        "on-tertiary-fixed": "#071e27",
        "surface-dim": "#d9dadb",
        "surface": "#f8f9fa",
        "error-container": "#ffdad6",
        brand: {
          50:  '#eef2ff',
          100: '#e0e7ff',
          200: '#c7d2fe',
          300: '#a5b4fc',
          400: '#818cf8',
          500: '#6366f1',
          600: '#4f46e5',
          700: '#4338ca',
          800: '#3730a3',
          900: '#312e81',
          950: '#1e1b4b',
        },
        accent: {
          50:  '#f0f9ff',
          100: '#e0f2fe',
          200: '#bae6fd',
          300: '#7dd3fc',
          400: '#38bdf8',
          500: '#0ea5e9',
          600: '#0284c7',
          700: '#0369a1',
          800: '#075985',
          900: '#0c4a6e',
        },
        surface_old: {
          50:  '#f8fafc',
          100: '#f1f5f9',
          200: '#e2e8f0',
          300: '#cbd5e1',
          400: '#94a3b8',
          500: '#64748b',
          600: '#475569',
          700: '#334155',
          800: '#1e293b',
          900: '#0f172a',
          950: '#020617',
        },
      },
      borderRadius: {
        lg: 'var(--radius)',
        md: 'calc(var(--radius) - 2px)',
        sm: 'calc(var(--radius) - 4px)',
        xl: '0.75rem',
        '2xl': '1rem',
        '3xl': '1.5rem',
      },
      fontFamily: {
        headline: ['Manrope', 'sans-serif'],
        body: ['Inter', 'sans-serif'],
        label: ['Inter', 'sans-serif'],
        sans: ['Inter', 'ui-sans-serif', 'system-ui'],
        mono: ['JetBrains Mono', 'ui-monospace', 'monospace'],
      },
      backgroundImage: {
        'gradient-brand': 'linear-gradient(135deg, #6366f1 0%, #0ea5e9 100%)',
        'gradient-dark':  'linear-gradient(135deg, #0f172a 0%, #1e293b 100%)',
        'gradient-glass': 'linear-gradient(135deg, rgba(255,255,255,0.05) 0%, rgba(255,255,255,0.02) 100%)',
      },
      boxShadow: {
        'glow-brand': '0 0 20px rgba(99,102,241,0.35)',
        'glow-accent': '0 0 20px rgba(14,165,233,0.35)',
        'glow-success': '0 0 20px rgba(16,185,129,0.35)',
        'glass': '0 8px 32px rgba(0,0,0,0.3)',
        'card': '0 4px 24px rgba(0,0,0,0.2)',
      },
      backdropBlur: {
        xs: '2px',
      },
      animation: {
        'fade-in':     'fadeIn 0.3s ease-out',
        'slide-up':    'slideUp 0.4s ease-out',
        'slide-in':    'slideIn 0.3s ease-out',
        'pulse-slow':  'pulse 3s cubic-bezier(0.4, 0, 0.6, 1) infinite',
        'spin-slow':   'spin 3s linear infinite',
        'bounce-soft': 'bounceSoft 1s ease-in-out infinite',
      },
      keyframes: {
        fadeIn:    { from: { opacity: '0' }, to: { opacity: '1' } },
        slideUp:   { from: { opacity: '0', transform: 'translateY(20px)' }, to: { opacity: '1', transform: 'translateY(0)' } },
        slideIn:   { from: { opacity: '0', transform: 'translateX(-20px)' }, to: { opacity: '1', transform: 'translateX(0)' } },
        bounceSoft:{ '0%, 100%': { transform: 'translateY(-4px)' }, '50%': { transform: 'translateY(0)' } },
      },
    },
  },
  plugins: [],
};
